V0.2.x/refactoring - FrontEnd
sighupio/fury-connect-switch pull request #26
Opened 2021-06-29 17:02 UTC by Al-Pragliola

Hello,

This PR aims to improve frontend structure and logic, those improvements will set up a common ground for future fury dashboard components.

Co-Author: @Rampage1xx

2021-06-29 18:31 UTC, Rampage1xx requested changes

2021-06-29 18:31 UTC, Rampage1xx commented on web-client/src/constants.ts
> +}
needs new line

2021-06-29 18:31 UTC, Rampage1xx commented on web-client/src/custom.d.ts
> +}
needs new line

2021-06-29 18:31 UTC, Rampage1xx commented on web-client/src/Components/SwitchUi/LocalizedText.ts
> +}
needs new line

2021-06-29 18:31 UTC, Rampage1xx commented on web-client/src/Components/ServiceCard/LocalizedText.ts
> +}
needs new line

2021-06-29 18:33 UTC, Rampage1xx commented
Check that every file ends with new line

2021-06-30 08:44 UTC, AndreaDellaValle commented on web-client/src/Services/BaseLocalizedText.ts
> +export class BaseLocalizedText {
@Rampage1xx @Al-Pragliola The i18n basic t() method it's already widely used (i mean, external non sighup projects), so I'm trying to figure out if this wrapping layer is really worth for our use cases (we don't have a blog or a article based platform), because we are asking people who wants to contribute to use this class as a standard here, perhaps: when do I need to put a logic like buttonStatus function here? What if the 'active' value changes? I would keep it simple with basic i18n implementation, but I'll wait for your feedbacks.

2021-06-30 08:45 UTC, AndreaDellaValle commented on web-client/src/Services/BaseLocalizedText.ts
> +}
newline here

2021-06-30 08:51 UTC, Rampage1xx commented on web-client/src/Services/BaseLocalizedText.ts
> +export class BaseLocalizedText {
Hello,

I think that using a standardized way to use translation does two good things:
a) enforces uniformity inside the codebase
b) centralizes all the translation logic

2021-06-30 08:53 UTC, AndreaDellaValle commented on web-client/src/Components/SwitchUi/Wrapper.tsx
> +export default SwitchUiWrapper;
needs new line

2021-06-30 08:54 UTC, AndreaDellaValle commented on web-client/src/Components/SwitchUi/index.ts
> +export { SwitchUiWrapper as SwitchUi };
needs new line

2021-06-30 09:08 UTC, Al-Pragliola commented on web-client/src/Components/FurySupport/Component.tsx
>  interface FurySupportComponentParams {
added readonly to all props in 8bf7390

2021-06-30 09:09 UTC, Al-Pragliola commented
added new lines and marked props as readonly in 8bf7390

2021-06-30 09:15 UTC, Al-Pragliola commented on web-client/src/Services/BaseLocalizedText.ts
> +export class BaseLocalizedText {
Extra effort of creating methods for every translation in a class saves you exponential time with IDE autocomplete, no more big search and replace in case of key changes, onboarding. I also think useful methods like buttonStatus avoid code replication in rendering methods and keeps them more clean

JM2C

2021-06-30 11:03 UTC, AndreaDellaValle approved these changes
LGTM !

2021-06-30 11:30 UTC, Rampage1xx approved these changes
LGTM

2021-06-30 12:53 UTC, merged